-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FULL_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL
);

-- Places table
CREATE TABLE IF NOT EXISTS PLACES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    PLACE_NAME TEXT,
    ADDRESS TEXT,
    LOCATION_LINK TEXT,
    IMAGE_URL TEXT,
    DESCRIPTION TEXT,
    VISITED BOOLEAN DEFAULT FALSE,
    IS_DRAFT BOOLEAN NOT NULL DEFAULT TRUE,
    STATUS TEXT CHECK(STATUS IN ('DRAFT', 'ACTIVE')) NOT NULL,
    UNIQUE(USER_ID, ID)
);

-- Carousel Images table (if using a separate table)
CREATE TABLE IF NOT EXISTS CAROUSEL_IMAGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PLACE_ID INTEGER NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
    IMAGE_URL TEXT NOT NULL
);